jobs:
  include:
    - stage: build
      name: win10_msvc2017_64_qt5_12_5_miniconda_latest
      language: bash
      os: windows
      services:
        - docker
      install:
        - pwd
        - choco install wget
        - choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        - PATH=$PATH:'/c/Program Files/CMake/bin' cmake --version
        - choco install -y visualstudio2017buildtools --allWorkloads --includeRecommended
        - choco install -y visualstudio2017-workload-vctools --package-parameters "--includeRecommended"
        - choco install 7zip.portable
        - ./install-qt.sh --version 5.12.5 --directory ~/Qt5.12.5 --toolchain win64_msvc2017_64 qtbase
        - ls ~
        - ls ~/Qt5.12.5
        - ls ~/Qt5.12.5/5.12.5
        - ls ~/Qt5.12.5/5.12.5/msvc2017_64
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin qmake --version
        - wget -nv https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
        - 'echo '' 
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        '' > miniconda-installer-noniteractive.bat'
        - cat miniconda-installer-noniteractive.bat
        - ./miniconda-installer-noniteractive.bat
        - ls ~
        - ls ~/Miniconda3
        - source ~/Miniconda3/etc/profile.d/conda.sh
        - conda activate base
        - conda --version
        - python --version
        - conda create -y -n BrainNowTfa
        - conda activate BrainNowTfa
        - conda install -y pyinstaller
        - pip install src/py
      script:
        - docker --version
        - pwd
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin qmake --version
        - mkdir build && cd build
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin cmake .. -G"Visual Studio 15 2017 Win64" -DCMAKE_PREFIX_PATH=$HOME/Qt5.12.5/5.12.5/msvc2017_64/lib/cmake
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin cmake --build . --config Release
        - cd ..
        - source ~/Miniconda3/etc/profile.d/conda.sh
        - conda activate base
        - python --version
        - conda --version
        - cd src/py
        - conda activate BrainNowTfa
        - pyinstaller tfa.spec
        - cd ../..
      after_success:
        - pwd
        - cd build/bin/Release
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin windeployqt --release BrainNowTfa.exe
        - cp -r ../../../src/py/dist/tfa/* .
        - ls
        - cd ..
        - tar -cvaf Release.tar.gz Release
        - ls

    - stage: build
      name: win10_msvc2015_64_qt5_12_5_miniconda_latest
      language: bash
      os: windows
      services:
        - docker
      install:
        - pwd
        - choco install wget
        - choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
        - PATH=$PATH:'/c/Program Files/CMake/bin' cmake --version
        - choco install -y microsoft-visual-cpp-build-tools
        - choco install 7zip.portable
        - ./install-qt.sh --version 5.12.5 --directory ~/Qt5.12.5 --toolchain win64_msvc2015_64 qtbase
        - ls ~
        - ls ~/Qt5.12.5
        - ls ~/Qt5.12.5/5.12.5
        - ls ~/Qt5.12.5/5.12.5/msvc2015_64
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2015_64/bin qmake --version
        - wget -nv https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe
        - 'echo '' 
          start /wait "" Miniconda3-latest-Windows-x86_64.exe /InstallationType=AllUsers /AddToPath=1 /RegisterPython=1 /S /D=%UserProfile%\Miniconda3
        '' > miniconda-installer-noniteractive.bat'
        - cat miniconda-installer-noniteractive.bat
        - ./miniconda-installer-noniteractive.bat
        - ls ~
        - ls ~/Miniconda3
        - source ~/Miniconda3/etc/profile.d/conda.sh
        - conda activate base
        - conda --version
        - python --version
        - conda create -y -n BrainNowTfa
        - conda activate BrainNowTfa
        - conda install -y pyinstaller
        - pip install src/py
      script:
        - docker --version
        - pwd
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2015_64/bin qmake --version
        - mkdir build && cd build
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin cmake .. -G"Visual Studio 14 2015 Win64" -DCMAKE_PREFIX_PATH=$HOME/Qt5.12.5/5.12.5/msvc2015_64/lib/cmake
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2017_64/bin cmake --build . --config Release
        - cd ..
        - source ~/Miniconda3/etc/profile.d/conda.sh
        - conda activate base
        - python --version
        - conda --version
        - cd src/py
        - conda activate BrainNowTfa
        - pyinstaller tfa.spec
        - cd ../..
      after_success:
        - pwd
        - cd build/bin/Release
        - PATH=$PATH:$HOME/Qt5.12.5/5.12.5/msvc2015_64/bin windeployqt --release BrainNowTfa.exe
        - cp -r ../../../src/py/dist/tfa/* .
        - ls
        - cd ..
        - tar -cvaf Release.tar.gz Release
        - ls
      deploy:
        provider: releases
        token: $GITHUB_TOKEN
        file: build/bin/Release.tar.gz
        edge: true
        on: 
          branch: master
          tags: true

stages: build